### PR TITLE
Denisacostaq t27 metrics as proxy fix bugs

### LINKED ISSUE #27: Metrics as proxy - fix bugs
Bugs:
- [x] An invalid metrics endpoint can make the program panic.

- [x] Invalid metric name prefix when you found two metrics in which the names are relatein in a prefix/sufix scheme. For example, `my_custom_metric_name`, `my_custom_metric_name_for_test`, sufix `_for_test`

PD: write tests for thouse cases

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #27 

some tests for the bugs, and correction

### CODE REVIEW

File: src/config/service.go [hunk 1]
```diff
@@ -97,6 +100,9 @@ func (srv Service) validateAPIRest() (errs []error) {
 			errs = append(errs, errors.New("can not create a valid url to get metric: "+srv.URIToGetMetric(metric)))
 		}
 	}
+	if len(srv.AuthType) == 0 {
```
Comment (olemis) [inline src/config/service.go]: some public services do require authentication

**Review by olemis — CHANGES_REQUESTED** [review]

**Review by olemis — APPROVED** [review]
